### ISSUE TITLE
Feature request: Add pyproject.toml to enable installing the package via pip

### ISSUE THREAD

**Issue by jonathanlarochelle** [esl-epfl/sz-validation-framework#1]
Hi,
I would be interested in using the timescoring functions in my analysis scripts. They would be easier to integrate if the package could be installed. The package does not need to be on Pypi, it would suffice to have a pyproject.toml in the root directory, and place all the python code in a directory with a name like 'sz-validation-framework'. It could then be installed via

pip install git+https://github.com/esl-epfl/sz-validation-framework.git

Reference for writing pyproject.toml: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

Cheers,
Jonathan

**Comment by jon-dan** [comment]
Sorry for the late reponse!
I only just saw your message.

The timescoring package is already available on Pypi

You will find more info in the Readme of the package: https://github.com/esl-epfl/timescoring

**Comment by jonathanlarochelle** [comment]
Thank you for the missing, I missed that!

Cheers.
